image:
  file: .gitpod.Dockerfile

tasks:
  - init: . ./.gitpod/initialize.sh
  - command:  cd demos

github:
  prebuilds:
    branches: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - jpoissonnier.vscode-styled-components
    - styled-components.vscode-styled-components
