image:
  file: .gitpod.Dockerfile

tasks:
  - init: |-
      git submodule update --init --recursive && git submodule update --recursive
      (cd docs && yarn install) && (cd contributor-cli && yarn install) && (cd lib && yarn install)
  - command: echo "Welcome to Chewy!"

github:
  prebuilds:
    branches: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - jpoissonnier.vscode-styled-components
    - styled-components.vscode-styled-components
