image:
  file: .gitpod.Dockerfile

tasks:
  - init: (cd docs && yarn install) && (cd chewy-contributor-cli && yarn install) && (cd lib && yarn install)
  - command: echo "Welcome to Chewy!"

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - jpoissonnier.vscode-styled-components
    - styled-components.vscode-styled-components
